import { Technician, WorkOrder } from "@/src/features/operations/types";

export const initialTechnicians: Technician[] = [
  {
    id: "tec-01",
    name: "Ana López",
    zone: "Barcelona Norte",
    location: { lat: 41.4182, lng: 2.1734 },
    skills: ["CCS", "AC Type 2", "Diagnóstico remoto"],
    status: "available",
    lastCheckIn: "08:12",
  },
  {
    id: "tec-02",
    name: "Javier Martín",
    zone: "Barcelona Sur",
    location: { lat: 41.3597, lng: 2.1388 },
    skills: ["CCS", "Mantenimiento preventivo"],
    status: "on_route",
    activeOrderId: "ot-2026-104",
    lastCheckIn: "08:40",
  },
  {
    id: "tec-03",
    name: "Lucía Pérez",
    zone: "Tarragona",
    location: { lat: 41.1178, lng: 1.2445 },
    skills: ["CHAdeMO", "AC Type 2"],
    status: "working",
    activeOrderId: "ot-2026-106",
    lastCheckIn: "08:51",
  },
  {
    id: "tec-04",
    name: "Miguel Torres",
    zone: "Girona",
    location: { lat: 41.9831, lng: 2.8249 },
    skills: ["CCS", "CHAdeMO", "Puesta en marcha"],
    status: "available",
    lastCheckIn: "08:55",
  },
  {
    id: "tec-05",
    name: "Nora Ruiz",
    zone: "Lleida",
    location: { lat: 41.6176, lng: 0.62 },
    skills: ["AC Type 2", "Mantenimiento preventivo"],
    status: "offline",
    lastCheckIn: "07:20",
  },
];

export const initialWorkOrders: WorkOrder[] = [
  {
    id: "ot-2026-104",
    siteName: "Parking Centro Mar",
    city: "Barcelona",
    address: "Carrer de la Marina 42",
    createdAt: "2026-03-26T06:20:00Z",
    connectorType: "CCS",
    priority: "correctivo_critico",
    status: "assigned",
    scheduledAt: "09:00",
    notes: "Fallo de comunicación OCPP intermitente.",
    technicianId: "tec-02",
  },
  {
    id: "ot-2026-105",
    siteName: "Hotel Delta",
    city: "Tarragona",
    address: "Avinguda Roma 8",
    createdAt: "2026-03-26T08:05:00Z",
    connectorType: "AC Type 2",
    priority: "mantenimiento_preventivo_programado",
    status: "pending",
    scheduledAt: "10:30",
    notes: "Revisión de mantenimiento trimestral.",
  },
  {
    id: "ot-2026-106",
    siteName: "Supermercado Plana",
    city: "Reus",
    address: "Carrer Major 77",
    createdAt: "2026-03-25T22:40:00Z",
    connectorType: "CHAdeMO",
    priority: "visita_diagnostico",
    status: "in_progress",
    scheduledAt: "08:30",
    notes: "Cargador no entrega potencia nominal.",
    technicianId: "tec-03",
  },
  {
    id: "ot-2026-107",
    siteName: "Área de Servicio AP-7",
    city: "Girona",
    address: "Salida 9 AP-7",
    createdAt: "2026-03-24T17:10:00Z",
    connectorType: "CCS",
    priority: "correctivo_no_critico",
    status: "pending",
    scheduledAt: "12:00",
    notes: "Actualización de firmware planificada.",
  },
];

