import { Technician, WorkOrder } from "@/src/features/operations/types";

export const initialTechnicians: Technician[] = [
  {
    id: "tec-01",
    name: "Ana Lopez",
    zone: "Barcelona Norte",
    skills: ["CCS", "AC Type 2", "Diagnostico remoto"],
    status: "available",
    lastCheckIn: "08:12",
  },
  {
    id: "tec-02",
    name: "Javier Martin",
    zone: "Barcelona Sur",
    skills: ["CCS", "Mantenimiento preventivo"],
    status: "on_route",
    activeOrderId: "ot-2026-104",
    lastCheckIn: "08:40",
  },
  {
    id: "tec-03",
    name: "Lucia Perez",
    zone: "Tarragona",
    skills: ["CHAdeMO", "AC Type 2"],
    status: "working",
    activeOrderId: "ot-2026-106",
    lastCheckIn: "08:51",
  },
  {
    id: "tec-04",
    name: "Miguel Torres",
    zone: "Girona",
    skills: ["CCS", "CHAdeMO", "Puesta en marcha"],
    status: "available",
    lastCheckIn: "08:55",
  },
  {
    id: "tec-05",
    name: "Nora Ruiz",
    zone: "Lleida",
    skills: ["AC Type 2", "Mantenimiento preventivo"],
    status: "offline",
    lastCheckIn: "07:20",
  },
];

export const initialWorkOrders: WorkOrder[] = [
  {
    id: "ot-2026-104",
    siteName: "Parking Centro Mar",
    city: "Barcelona",
    address: "Carrer de la Marina 42",
    connectorType: "CCS",
    priority: "high",
    status: "assigned",
    scheduledAt: "09:00",
    notes: "Fallo de comunicacion OCPP intermitente.",
    technicianId: "tec-02",
  },
  {
    id: "ot-2026-105",
    siteName: "Hotel Delta",
    city: "Tarragona",
    address: "Avinguda Roma 8",
    connectorType: "AC Type 2",
    priority: "medium",
    status: "pending",
    scheduledAt: "10:30",
    notes: "Revision de mantenimiento trimestral.",
  },
  {
    id: "ot-2026-106",
    siteName: "Supermercado Plana",
    city: "Reus",
    address: "Carrer Major 77",
    connectorType: "CHAdeMO",
    priority: "high",
    status: "in_progress",
    scheduledAt: "08:30",
    notes: "Cargador no entrega potencia nominal.",
    technicianId: "tec-03",
  },
  {
    id: "ot-2026-107",
    siteName: "Area de Servicio AP-7",
    city: "Girona",
    address: "Salida 9 AP-7",
    connectorType: "CCS",
    priority: "low",
    status: "pending",
    scheduledAt: "12:00",
    notes: "Actualizacion de firmware planificada.",
  },
];

