import { Technician, WorkOrder } from "@/src/features/operations/types";

export const initialTechnicians: Technician[] = [
  {
    id: "tec-01",
    name: "Ana López",
    zone: "Barcelona Norte",
    location: { lat: 41.4182, lng: 2.1734 },
    skills: ["CCS", "AC Type 2", "Diagnóstico remoto"],
    status: "available",
    lastCheckIn: "08:12",
  },
  {
    id: "tec-02",
    name: "Javier Martín",
    zone: "Barcelona Sur",
    location: { lat: 41.3597, lng: 2.1388 },
    skills: ["CCS", "Mantenimiento preventivo"],
    status: "on_route",
    activeOrderId: 1,
    lastCheckIn: "08:40",
  },
  {
    id: "tec-03",
    name: "Lucía Pérez",
    zone: "Tarragona",
    location: { lat: 41.1178, lng: 1.2445 },
    skills: ["CHAdeMO", "AC Type 2"],
    status: "working",
    activeOrderId: 3,
    lastCheckIn: "08:51",
  },
  {
    id: "tec-04",
    name: "Miguel Torres",
    zone: "Girona",
    location: { lat: 41.9831, lng: 2.8249 },
    skills: ["CCS", "CHAdeMO", "Puesta en marcha"],
    status: "available",
    lastCheckIn: "08:55",
  },
  {
    id: "tec-05",
    name: "Nora Ruiz",
    zone: "Lleida",
    location: { lat: 41.6176, lng: 0.62 },
    skills: ["AC Type 2", "Mantenimiento preventivo"],
    status: "offline",
    lastCheckIn: "07:20",
  },
];

export const initialWorkOrders: WorkOrder[] = [
  {
    incidence_id: 1,
    charger_id: 15,
    reported_at: "2024-12-11T03:15:50.555645",
    priority: "Visita de diagnosi",
    status: "Tancada",
    description: "Error generat per a entrenament",
    estimated_duration_min: 84,
    final_duration_min: 53,
    resolved_at: "2024-12-11T04:08:50.555645",
    technicianId: "tec-02",
  },
  {
    incidence_id: 2,
    charger_id: 12,
    reported_at: "2024-12-11T05:10:10.000000",
    priority: "Manteniment preventiu",
    status: "Nova",
    description: "Pèrdua de comunicació intermitent",
    estimated_duration_min: 60,
  },
  {
    incidence_id: 3,
    charger_id: 21,
    reported_at: "2024-12-11T06:20:00.000000",
    priority: "Reparació crítica",
    status: "En curs",
    description: "El carregador no entrega potència nominal",
    estimated_duration_min: 120,
    technicianId: "tec-03",
  },
  {
    incidence_id: 4,
    charger_id: 9,
    reported_at: "2024-12-11T07:45:00.000000",
    priority: "Visita de diagnosi",
    status: "Assignada",
    description: "Actualització de firmware planificada",
    estimated_duration_min: 45,
    technicianId: "tec-01",
  },
];

